MichaelAquilina/zsh-autoswitch-virtualenv

README.md

* Add zgen instructions
* Make spacing between sections consistent
* Minor phrasing changes in README.md

Add zgen instructions

---

README.md
autoswitch_virtualenv.plugin.zsh

Dont deactivate a virtualenv if its a subdirectory of a project

---

autoswitch_virtualenv.plugin.zsh

Warn the user when a .venv file has weak permissions

---

autoswitch_virtualenv.plugin.zsh
tests/test_check_venv_path.zunit

Use chpwd instead of precmd

---

CHANGELOG.rst
tests/test_check_venv.zunit
tests/test_mkvenv.zunit

* Add tests for mkvenv and check_venv

Add tests for check_venv

---

CHANGELOG.rst
autoswitch_virtualenv.plugin.zsh
tests/test_check_venv.zunit
tests/test_check_venv_path.zunit
tests/test_help.zunit

* Disable plugin and print help message if virtualenvwrapper not setup correctly (Fixes #15)
* Fix bug in rmvenv when no virtualenv was activated
* Fix flaky tests

Release 0.3.0

---

README.rst
autoswitch_virtualenv.plugin.zsh
tests/test_help.zunit

Link to README setup in help message

---

autoswitch_virtualenv.plugin.zsh
tests/test_check_venv.zunit

Prefix old PWD variable to prevent prezto from acting strangely

---

CHANGELOG.rst
autoswitch_virtualenv.plugin.zsh
tests/test_install_requirements.txt
tests/test_maybeworkon.zunit
tests/test_mkvenv.zunit
tests/test_rmvenv.zunit

Fixes issue #79
TODO
@posquit0 could you test this out locally and let me know if this fixes your problem?

Fix pipenv integration

---

CHANGELOG.rst
README.rst
autoswitch_virtualenv.plugin.zsh

1.8.2 release

---

README.rst

Improve documentation mentioning system-site-packages

---

README.rst
autoswitch_virtualenv.plugin.zsh
tests/test_install_requirements.zunit

Install by default in editable/development mode.

---

README.rst

Make oh-my-zsh README instructions clearer about position of plugin line

---

CHANGELOG.rst
autoswitch_virtualenv.plugin.zsh
tests/test_check_venv.zunit

Questions:
* Is `pipenv install` the correct command to suggest considering it wont automatically switch to the correct virtualenv the first time?

Release 1.11.0

---

autoswitch_virtualenv.plugin.zsh
tests/test_check_venv.zunit
tests/test_get_venv_type.zunit
tests/test_maybeworkon.zunit

Better pipenv names

---

CHANGELOG.rst
autoswitch_virtualenv.plugin.zsh

Use fixed stat path to work round other possible stat binaries in $PATH

---

CHANGELOG.rst
autoswitch_virtualenv.plugin.zsh
tests/test_maybeworkon.zunit

fix: insecure activation of virtualenvs

---

CHANGELOG.rst
README.rst
autoswitch_virtualenv.plugin.zsh
tests/test_check_venv.zunit
tests/test_get_venv_type.zunit
tests/test_mkvenv.zunit
tests/test_rmvenv.zunit

Improved integration of pipenv and poetry

---

CHANGELOG.rst
autoswitch_virtualenv.plugin.zsh
tests/test_check_path.zunit
tests/test_check_venv.zunit

Correctly detect poetry virtualenv location

---

ISSUE_TEMPLATE.md

fix: issue template

---

README.rst
autoswitch_virtualenv.plugin.zsh
tests/test_mkvenv.zunit
tests/test_plugin.zunit

We seem to make pretty minimal use of pwgen, and since it's a little bit bothersome to have an additional install everywhere I set up my shell, I figured a couple lines of rolling our own might be better.
Fixes #165

Remove pwgen dependency

---

README.rst
autoswitch_virtualenv.plugin.zsh
tests/test_check_path.zunit
tests/test_check_venv.zunit

Implement proposal https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv/issues/140#issuecomment-685901973.
This is just the code change, let's see how you feel about this before looking at doc and tests.

If AUTOSWITCH_FILE is not a file but a virtualenv, activate it

---

autoswitch_virtualenv.plugin.zsh

check python if AUTOSWITCH_DEFAULT_PYTHON is set

---

autoswitch_virtualenv.plugin.zsh

Fix a variable reference missed in #190.
Should fix some test failures.

Fix color variable name
